### PR TITLE
Allow vinkla/hashids 12 for Laravel 11 support

### LINKED ISSUE #83: Laravel 11 support
vinkla/hashids should be version 12 to support laravel 11

### PR DESCRIPTION
**Pull request by beschoenen**
Allows vinkla/hashids 11 & 12 for Laravel 10 & 11 support.

Fixes #83

### CODE REVIEW

**Comment by ozamorowski** [comment]
Hello, is there any reason why this isn't merged yet? This package is the last holding me from upgrade to laravel 11...

**Comment by beschoenen** [comment]
@ozamorowski I'm using this in the project where I need rinvex/laravel-support right now as a workaround.

```
"vinkla/hashids": "12.0.0 as 11.0.0"
```

**Comment by ozamorowski** [comment]
> ```
> "vinkla/hashids": "12.0.0 as 11.0.0"
> ```

@beschoenen That works. Thanks!

**Comment by beschoenen** [comment]
@Omranic Can you have a look?

**Pull request merged**
